name: Test

on:
    push: ~
    pull_request: ~

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4

            -   name: Start MySQL container
                run: |
                    docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=sylius_plugin mysql:8.0

            -   name: Start PHP container
                run: |
                    docker run -d --name web \
                    -e PHP_INI_MEMORY_LIMIT=8G \
                    -e PHP_EXTENSIONS="intl gd" \
                    -e MYSQL_DATABASE=sylius_plugin \
                    -e MYSQL_ROOT_PASSWORD=root \
                    -e MYSQL_USER=root \
                    thecodingmachine/php:8.3-v4-cli

            # -   name: Validate composer.json and composer.lock
            #     run: composer validate --strict

            -   name: Install Composer dependencies
                run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

            -   name: Run PHPStan
                run: composer phpstan

            -   name: Run PHP Code Sniffer
                run: composer cscheck
