name: Test

on:
    push: ~
    pull_request: ~

permissions:
    contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        container:
            image: thecodingmachine/php:8.3-v4-cli
        steps:
            # -   uses: actions/checkout@v4

            # -   name: Validate composer.json and composer.lock
            #     run: composer validate --strict

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run PHPStan
                run: composer phpstan

            -   name: Run PHP Code Sniffer
                run: composer cscheck
