name: Test

on:
    push: ~
    pull_request: ~

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            -   use: mysql:8.0
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: sylius_plugin

            -   use: thecodingmachine/php:8.3-v4-cli
                env:
                    PHP_INI_MEMORY_LIMIT: "8G"
                    PHP_EXTENSIONS: "intl gd"
                    MYSQL_DATABASE: sylius_plugin
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_USER: root

            -   uses: actions/checkout@v4

            # -   name: Validate composer.json and composer.lock
            #     run: composer validate --strict

            -   name: Install Composer dependencies
                run: composer install --prefer-dist --no-progress

            -   name: Run PHPStan
                run: composer phpstan

            -   name: Run PHP Code Sniffer
                run: composer cscheck
