name: Test

on:
    push: ~
    pull_request: ~

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [ "8.3" ]
                mysql: [ "8.3" ]
        steps:
            -   uses: actions/checkout@v4

            -   name: Setup MySQL
                uses: mirromutth/mysql-action@v1.1
                with:
                    mysql version: "${{ matrix.mysql }}"
                    mysql root password: "password"

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: "${{ matrix.php }}"

            -   name: Cache Composer
                uses: actions/cache@v3
                with:
                    path: vendor
                    key: ${{ runner.os }}-php-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json **/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-php-${{ matrix.php }}-composer-

            -   name: Copy .env file
                run: cp .env.template .env

            -   name: Clone Backoffice sylius plugin
                run: git clone -b main https://github.com/ayman-benmada/Sylius-Backoffice-Plugin.git plugin/BackofficePlugin

            -   name: Install composer dependencies
                run: composer install --prefer-dist --no-interaction --ansi

            -   name: Run PHPStan
                run: composer phpstan

            -   name: Run PHP Code Sniffer
                run: composer cscheck
